/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ClientsIndexImport } from './routes/clients/index'
import { Route as ClientsNewImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId/route'
import { Route as ClientsClientIdIndexImport } from './routes/clients/$clientId/index'
import { Route as ClientsClientIdOtherAssetsRouteImport } from './routes/clients/$clientId/other-assets/route'
import { Route as ClientsClientIdAccountsRouteImport } from './routes/clients/$clientId/accounts/route'
import { Route as ClientsClientIdOtherAssetsIndexImport } from './routes/clients/$clientId/other-assets/index'
import { Route as ClientsClientIdAccountsIndexImport } from './routes/clients/$clientId/accounts/index'
import { Route as ClientsClientIdOtherAssetsNewImport } from './routes/clients/$clientId/other-assets/new'
import { Route as ClientsClientIdAccountsNewImport } from './routes/clients/$clientId/accounts/new'
import { Route as ClientsClientIdOtherAssetsAssetIdRouteImport } from './routes/clients/$clientId/other-assets/$assetId/route'
import { Route as ClientsClientIdAccountsAccountIdRouteImport } from './routes/clients/$clientId/accounts/$accountId/route'
import { Route as ClientsClientIdOtherAssetsAssetIdIndexImport } from './routes/clients/$clientId/other-assets/$assetId/index'
import { Route as ClientsClientIdAccountsAccountIdIndexImport } from './routes/clients/$clientId/accounts/$accountId/index'
import { Route as ClientsClientIdAccountsAccountIdTransactionsRouteImport } from './routes/clients/$clientId/accounts/$accountId/transactions/route'
import { Route as ClientsClientIdAccountsAccountIdTransactionsIndexImport } from './routes/clients/$clientId/accounts/$accountId/transactions/index'
import { Route as ClientsClientIdAccountsAccountIdTransactionsNewImport } from './routes/clients/$clientId/accounts/$accountId/transactions/new'
import { Route as ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteImport } from './routes/clients/$clientId/accounts/$accountId/transactions/$transactionId/route'
import { Route as ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexImport } from './routes/clients/$clientId/accounts/$accountId/transactions/$transactionId/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClientsIndexRoute = ClientsIndexImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRoute,
} as any)

const ClientsNewRoute = ClientsNewImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRoute,
} as any)

const ClientsClientIdRouteRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRoute,
} as any)

const ClientsClientIdIndexRoute = ClientsClientIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsClientIdRouteRoute,
} as any)

const ClientsClientIdOtherAssetsRouteRoute =
  ClientsClientIdOtherAssetsRouteImport.update({
    id: '/other-assets',
    path: '/other-assets',
    getParentRoute: () => ClientsClientIdRouteRoute,
  } as any)

const ClientsClientIdAccountsRouteRoute =
  ClientsClientIdAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => ClientsClientIdRouteRoute,
  } as any)

const ClientsClientIdOtherAssetsIndexRoute =
  ClientsClientIdOtherAssetsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientsClientIdOtherAssetsRouteRoute,
  } as any)

const ClientsClientIdAccountsIndexRoute =
  ClientsClientIdAccountsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientsClientIdAccountsRouteRoute,
  } as any)

const ClientsClientIdOtherAssetsNewRoute =
  ClientsClientIdOtherAssetsNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ClientsClientIdOtherAssetsRouteRoute,
  } as any)

const ClientsClientIdAccountsNewRoute = ClientsClientIdAccountsNewImport.update(
  {
    id: '/new',
    path: '/new',
    getParentRoute: () => ClientsClientIdAccountsRouteRoute,
  } as any,
)

const ClientsClientIdOtherAssetsAssetIdRouteRoute =
  ClientsClientIdOtherAssetsAssetIdRouteImport.update({
    id: '/$assetId',
    path: '/$assetId',
    getParentRoute: () => ClientsClientIdOtherAssetsRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdRouteRoute =
  ClientsClientIdAccountsAccountIdRouteImport.update({
    id: '/$accountId',
    path: '/$accountId',
    getParentRoute: () => ClientsClientIdAccountsRouteRoute,
  } as any)

const ClientsClientIdOtherAssetsAssetIdIndexRoute =
  ClientsClientIdOtherAssetsAssetIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientsClientIdOtherAssetsAssetIdRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdIndexRoute =
  ClientsClientIdAccountsAccountIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ClientsClientIdAccountsAccountIdRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdTransactionsRouteRoute =
  ClientsClientIdAccountsAccountIdTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => ClientsClientIdAccountsAccountIdRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdTransactionsIndexRoute =
  ClientsClientIdAccountsAccountIdTransactionsIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ClientsClientIdAccountsAccountIdTransactionsRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdTransactionsNewRoute =
  ClientsClientIdAccountsAccountIdTransactionsNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () =>
      ClientsClientIdAccountsAccountIdTransactionsRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRoute =
  ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () =>
      ClientsClientIdAccountsAccountIdTransactionsRouteRoute,
  } as any)

const ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute =
  ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewImport
      parentRoute: typeof rootRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexImport
      parentRoute: typeof rootRoute
    }
    '/clients/$clientId/accounts': {
      id: '/clients/$clientId/accounts'
      path: '/accounts'
      fullPath: '/clients/$clientId/accounts'
      preLoaderRoute: typeof ClientsClientIdAccountsRouteImport
      parentRoute: typeof ClientsClientIdRouteImport
    }
    '/clients/$clientId/other-assets': {
      id: '/clients/$clientId/other-assets'
      path: '/other-assets'
      fullPath: '/clients/$clientId/other-assets'
      preLoaderRoute: typeof ClientsClientIdOtherAssetsRouteImport
      parentRoute: typeof ClientsClientIdRouteImport
    }
    '/clients/$clientId/': {
      id: '/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof ClientsClientIdIndexImport
      parentRoute: typeof ClientsClientIdRouteImport
    }
    '/clients/$clientId/accounts/$accountId': {
      id: '/clients/$clientId/accounts/$accountId'
      path: '/$accountId'
      fullPath: '/clients/$clientId/accounts/$accountId'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdRouteImport
      parentRoute: typeof ClientsClientIdAccountsRouteImport
    }
    '/clients/$clientId/other-assets/$assetId': {
      id: '/clients/$clientId/other-assets/$assetId'
      path: '/$assetId'
      fullPath: '/clients/$clientId/other-assets/$assetId'
      preLoaderRoute: typeof ClientsClientIdOtherAssetsAssetIdRouteImport
      parentRoute: typeof ClientsClientIdOtherAssetsRouteImport
    }
    '/clients/$clientId/accounts/new': {
      id: '/clients/$clientId/accounts/new'
      path: '/new'
      fullPath: '/clients/$clientId/accounts/new'
      preLoaderRoute: typeof ClientsClientIdAccountsNewImport
      parentRoute: typeof ClientsClientIdAccountsRouteImport
    }
    '/clients/$clientId/other-assets/new': {
      id: '/clients/$clientId/other-assets/new'
      path: '/new'
      fullPath: '/clients/$clientId/other-assets/new'
      preLoaderRoute: typeof ClientsClientIdOtherAssetsNewImport
      parentRoute: typeof ClientsClientIdOtherAssetsRouteImport
    }
    '/clients/$clientId/accounts/': {
      id: '/clients/$clientId/accounts/'
      path: '/'
      fullPath: '/clients/$clientId/accounts/'
      preLoaderRoute: typeof ClientsClientIdAccountsIndexImport
      parentRoute: typeof ClientsClientIdAccountsRouteImport
    }
    '/clients/$clientId/other-assets/': {
      id: '/clients/$clientId/other-assets/'
      path: '/'
      fullPath: '/clients/$clientId/other-assets/'
      preLoaderRoute: typeof ClientsClientIdOtherAssetsIndexImport
      parentRoute: typeof ClientsClientIdOtherAssetsRouteImport
    }
    '/clients/$clientId/accounts/$accountId/transactions': {
      id: '/clients/$clientId/accounts/$accountId/transactions'
      path: '/transactions'
      fullPath: '/clients/$clientId/accounts/$accountId/transactions'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdTransactionsRouteImport
      parentRoute: typeof ClientsClientIdAccountsAccountIdRouteImport
    }
    '/clients/$clientId/accounts/$accountId/': {
      id: '/clients/$clientId/accounts/$accountId/'
      path: '/'
      fullPath: '/clients/$clientId/accounts/$accountId/'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdIndexImport
      parentRoute: typeof ClientsClientIdAccountsAccountIdRouteImport
    }
    '/clients/$clientId/other-assets/$assetId/': {
      id: '/clients/$clientId/other-assets/$assetId/'
      path: '/'
      fullPath: '/clients/$clientId/other-assets/$assetId/'
      preLoaderRoute: typeof ClientsClientIdOtherAssetsAssetIdIndexImport
      parentRoute: typeof ClientsClientIdOtherAssetsAssetIdRouteImport
    }
    '/clients/$clientId/accounts/$accountId/transactions/$transactionId': {
      id: '/clients/$clientId/accounts/$accountId/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/clients/$clientId/accounts/$accountId/transactions/$transactionId'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteImport
      parentRoute: typeof ClientsClientIdAccountsAccountIdTransactionsRouteImport
    }
    '/clients/$clientId/accounts/$accountId/transactions/new': {
      id: '/clients/$clientId/accounts/$accountId/transactions/new'
      path: '/new'
      fullPath: '/clients/$clientId/accounts/$accountId/transactions/new'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdTransactionsNewImport
      parentRoute: typeof ClientsClientIdAccountsAccountIdTransactionsRouteImport
    }
    '/clients/$clientId/accounts/$accountId/transactions/': {
      id: '/clients/$clientId/accounts/$accountId/transactions/'
      path: '/'
      fullPath: '/clients/$clientId/accounts/$accountId/transactions/'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdTransactionsIndexImport
      parentRoute: typeof ClientsClientIdAccountsAccountIdTransactionsRouteImport
    }
    '/clients/$clientId/accounts/$accountId/transactions/$transactionId/': {
      id: '/clients/$clientId/accounts/$accountId/transactions/$transactionId/'
      path: '/'
      fullPath: '/clients/$clientId/accounts/$accountId/transactions/$transactionId/'
      preLoaderRoute: typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexImport
      parentRoute: typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteImport
    }
  }
}

// Create and export the route tree

interface ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteChildren {
  ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute: typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute
}

const ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteChildren: ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteChildren =
  {
    ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute:
      ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute,
  }

const ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteWithChildren =
  ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRoute._addFileChildren(
    ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteChildren,
  )

interface ClientsClientIdAccountsAccountIdTransactionsRouteRouteChildren {
  ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRoute: typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteWithChildren
  ClientsClientIdAccountsAccountIdTransactionsNewRoute: typeof ClientsClientIdAccountsAccountIdTransactionsNewRoute
  ClientsClientIdAccountsAccountIdTransactionsIndexRoute: typeof ClientsClientIdAccountsAccountIdTransactionsIndexRoute
}

const ClientsClientIdAccountsAccountIdTransactionsRouteRouteChildren: ClientsClientIdAccountsAccountIdTransactionsRouteRouteChildren =
  {
    ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRoute:
      ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteWithChildren,
    ClientsClientIdAccountsAccountIdTransactionsNewRoute:
      ClientsClientIdAccountsAccountIdTransactionsNewRoute,
    ClientsClientIdAccountsAccountIdTransactionsIndexRoute:
      ClientsClientIdAccountsAccountIdTransactionsIndexRoute,
  }

const ClientsClientIdAccountsAccountIdTransactionsRouteRouteWithChildren =
  ClientsClientIdAccountsAccountIdTransactionsRouteRoute._addFileChildren(
    ClientsClientIdAccountsAccountIdTransactionsRouteRouteChildren,
  )

interface ClientsClientIdAccountsAccountIdRouteRouteChildren {
  ClientsClientIdAccountsAccountIdTransactionsRouteRoute: typeof ClientsClientIdAccountsAccountIdTransactionsRouteRouteWithChildren
  ClientsClientIdAccountsAccountIdIndexRoute: typeof ClientsClientIdAccountsAccountIdIndexRoute
}

const ClientsClientIdAccountsAccountIdRouteRouteChildren: ClientsClientIdAccountsAccountIdRouteRouteChildren =
  {
    ClientsClientIdAccountsAccountIdTransactionsRouteRoute:
      ClientsClientIdAccountsAccountIdTransactionsRouteRouteWithChildren,
    ClientsClientIdAccountsAccountIdIndexRoute:
      ClientsClientIdAccountsAccountIdIndexRoute,
  }

const ClientsClientIdAccountsAccountIdRouteRouteWithChildren =
  ClientsClientIdAccountsAccountIdRouteRoute._addFileChildren(
    ClientsClientIdAccountsAccountIdRouteRouteChildren,
  )

interface ClientsClientIdAccountsRouteRouteChildren {
  ClientsClientIdAccountsAccountIdRouteRoute: typeof ClientsClientIdAccountsAccountIdRouteRouteWithChildren
  ClientsClientIdAccountsNewRoute: typeof ClientsClientIdAccountsNewRoute
  ClientsClientIdAccountsIndexRoute: typeof ClientsClientIdAccountsIndexRoute
}

const ClientsClientIdAccountsRouteRouteChildren: ClientsClientIdAccountsRouteRouteChildren =
  {
    ClientsClientIdAccountsAccountIdRouteRoute:
      ClientsClientIdAccountsAccountIdRouteRouteWithChildren,
    ClientsClientIdAccountsNewRoute: ClientsClientIdAccountsNewRoute,
    ClientsClientIdAccountsIndexRoute: ClientsClientIdAccountsIndexRoute,
  }

const ClientsClientIdAccountsRouteRouteWithChildren =
  ClientsClientIdAccountsRouteRoute._addFileChildren(
    ClientsClientIdAccountsRouteRouteChildren,
  )

interface ClientsClientIdOtherAssetsAssetIdRouteRouteChildren {
  ClientsClientIdOtherAssetsAssetIdIndexRoute: typeof ClientsClientIdOtherAssetsAssetIdIndexRoute
}

const ClientsClientIdOtherAssetsAssetIdRouteRouteChildren: ClientsClientIdOtherAssetsAssetIdRouteRouteChildren =
  {
    ClientsClientIdOtherAssetsAssetIdIndexRoute:
      ClientsClientIdOtherAssetsAssetIdIndexRoute,
  }

const ClientsClientIdOtherAssetsAssetIdRouteRouteWithChildren =
  ClientsClientIdOtherAssetsAssetIdRouteRoute._addFileChildren(
    ClientsClientIdOtherAssetsAssetIdRouteRouteChildren,
  )

interface ClientsClientIdOtherAssetsRouteRouteChildren {
  ClientsClientIdOtherAssetsAssetIdRouteRoute: typeof ClientsClientIdOtherAssetsAssetIdRouteRouteWithChildren
  ClientsClientIdOtherAssetsNewRoute: typeof ClientsClientIdOtherAssetsNewRoute
  ClientsClientIdOtherAssetsIndexRoute: typeof ClientsClientIdOtherAssetsIndexRoute
}

const ClientsClientIdOtherAssetsRouteRouteChildren: ClientsClientIdOtherAssetsRouteRouteChildren =
  {
    ClientsClientIdOtherAssetsAssetIdRouteRoute:
      ClientsClientIdOtherAssetsAssetIdRouteRouteWithChildren,
    ClientsClientIdOtherAssetsNewRoute: ClientsClientIdOtherAssetsNewRoute,
    ClientsClientIdOtherAssetsIndexRoute: ClientsClientIdOtherAssetsIndexRoute,
  }

const ClientsClientIdOtherAssetsRouteRouteWithChildren =
  ClientsClientIdOtherAssetsRouteRoute._addFileChildren(
    ClientsClientIdOtherAssetsRouteRouteChildren,
  )

interface ClientsClientIdRouteRouteChildren {
  ClientsClientIdAccountsRouteRoute: typeof ClientsClientIdAccountsRouteRouteWithChildren
  ClientsClientIdOtherAssetsRouteRoute: typeof ClientsClientIdOtherAssetsRouteRouteWithChildren
  ClientsClientIdIndexRoute: typeof ClientsClientIdIndexRoute
}

const ClientsClientIdRouteRouteChildren: ClientsClientIdRouteRouteChildren = {
  ClientsClientIdAccountsRouteRoute:
    ClientsClientIdAccountsRouteRouteWithChildren,
  ClientsClientIdOtherAssetsRouteRoute:
    ClientsClientIdOtherAssetsRouteRouteWithChildren,
  ClientsClientIdIndexRoute: ClientsClientIdIndexRoute,
}

const ClientsClientIdRouteRouteWithChildren =
  ClientsClientIdRouteRoute._addFileChildren(ClientsClientIdRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/clients/$clientId': typeof ClientsClientIdRouteRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/clients/$clientId/accounts': typeof ClientsClientIdAccountsRouteRouteWithChildren
  '/clients/$clientId/other-assets': typeof ClientsClientIdOtherAssetsRouteRouteWithChildren
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
  '/clients/$clientId/accounts/$accountId': typeof ClientsClientIdAccountsAccountIdRouteRouteWithChildren
  '/clients/$clientId/other-assets/$assetId': typeof ClientsClientIdOtherAssetsAssetIdRouteRouteWithChildren
  '/clients/$clientId/accounts/new': typeof ClientsClientIdAccountsNewRoute
  '/clients/$clientId/other-assets/new': typeof ClientsClientIdOtherAssetsNewRoute
  '/clients/$clientId/accounts/': typeof ClientsClientIdAccountsIndexRoute
  '/clients/$clientId/other-assets/': typeof ClientsClientIdOtherAssetsIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions': typeof ClientsClientIdAccountsAccountIdTransactionsRouteRouteWithChildren
  '/clients/$clientId/accounts/$accountId/': typeof ClientsClientIdAccountsAccountIdIndexRoute
  '/clients/$clientId/other-assets/$assetId/': typeof ClientsClientIdOtherAssetsAssetIdIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions/$transactionId': typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteWithChildren
  '/clients/$clientId/accounts/$accountId/transactions/new': typeof ClientsClientIdAccountsAccountIdTransactionsNewRoute
  '/clients/$clientId/accounts/$accountId/transactions/': typeof ClientsClientIdAccountsAccountIdTransactionsIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions/$transactionId/': typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/clients/new': typeof ClientsNewRoute
  '/clients': typeof ClientsIndexRoute
  '/clients/$clientId': typeof ClientsClientIdIndexRoute
  '/clients/$clientId/accounts/new': typeof ClientsClientIdAccountsNewRoute
  '/clients/$clientId/other-assets/new': typeof ClientsClientIdOtherAssetsNewRoute
  '/clients/$clientId/accounts': typeof ClientsClientIdAccountsIndexRoute
  '/clients/$clientId/other-assets': typeof ClientsClientIdOtherAssetsIndexRoute
  '/clients/$clientId/accounts/$accountId': typeof ClientsClientIdAccountsAccountIdIndexRoute
  '/clients/$clientId/other-assets/$assetId': typeof ClientsClientIdOtherAssetsAssetIdIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions/new': typeof ClientsClientIdAccountsAccountIdTransactionsNewRoute
  '/clients/$clientId/accounts/$accountId/transactions': typeof ClientsClientIdAccountsAccountIdTransactionsIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions/$transactionId': typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/clients/$clientId': typeof ClientsClientIdRouteRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/clients/$clientId/accounts': typeof ClientsClientIdAccountsRouteRouteWithChildren
  '/clients/$clientId/other-assets': typeof ClientsClientIdOtherAssetsRouteRouteWithChildren
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
  '/clients/$clientId/accounts/$accountId': typeof ClientsClientIdAccountsAccountIdRouteRouteWithChildren
  '/clients/$clientId/other-assets/$assetId': typeof ClientsClientIdOtherAssetsAssetIdRouteRouteWithChildren
  '/clients/$clientId/accounts/new': typeof ClientsClientIdAccountsNewRoute
  '/clients/$clientId/other-assets/new': typeof ClientsClientIdOtherAssetsNewRoute
  '/clients/$clientId/accounts/': typeof ClientsClientIdAccountsIndexRoute
  '/clients/$clientId/other-assets/': typeof ClientsClientIdOtherAssetsIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions': typeof ClientsClientIdAccountsAccountIdTransactionsRouteRouteWithChildren
  '/clients/$clientId/accounts/$accountId/': typeof ClientsClientIdAccountsAccountIdIndexRoute
  '/clients/$clientId/other-assets/$assetId/': typeof ClientsClientIdOtherAssetsAssetIdIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions/$transactionId': typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdRouteRouteWithChildren
  '/clients/$clientId/accounts/$accountId/transactions/new': typeof ClientsClientIdAccountsAccountIdTransactionsNewRoute
  '/clients/$clientId/accounts/$accountId/transactions/': typeof ClientsClientIdAccountsAccountIdTransactionsIndexRoute
  '/clients/$clientId/accounts/$accountId/transactions/$transactionId/': typeof ClientsClientIdAccountsAccountIdTransactionsTransactionIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/register'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients'
    | '/clients/$clientId/accounts'
    | '/clients/$clientId/other-assets'
    | '/clients/$clientId/'
    | '/clients/$clientId/accounts/$accountId'
    | '/clients/$clientId/other-assets/$assetId'
    | '/clients/$clientId/accounts/new'
    | '/clients/$clientId/other-assets/new'
    | '/clients/$clientId/accounts/'
    | '/clients/$clientId/other-assets/'
    | '/clients/$clientId/accounts/$accountId/transactions'
    | '/clients/$clientId/accounts/$accountId/'
    | '/clients/$clientId/other-assets/$assetId/'
    | '/clients/$clientId/accounts/$accountId/transactions/$transactionId'
    | '/clients/$clientId/accounts/$accountId/transactions/new'
    | '/clients/$clientId/accounts/$accountId/transactions/'
    | '/clients/$clientId/accounts/$accountId/transactions/$transactionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/register'
    | '/clients/new'
    | '/clients'
    | '/clients/$clientId'
    | '/clients/$clientId/accounts/new'
    | '/clients/$clientId/other-assets/new'
    | '/clients/$clientId/accounts'
    | '/clients/$clientId/other-assets'
    | '/clients/$clientId/accounts/$accountId'
    | '/clients/$clientId/other-assets/$assetId'
    | '/clients/$clientId/accounts/$accountId/transactions/new'
    | '/clients/$clientId/accounts/$accountId/transactions'
    | '/clients/$clientId/accounts/$accountId/transactions/$transactionId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/register'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/accounts'
    | '/clients/$clientId/other-assets'
    | '/clients/$clientId/'
    | '/clients/$clientId/accounts/$accountId'
    | '/clients/$clientId/other-assets/$assetId'
    | '/clients/$clientId/accounts/new'
    | '/clients/$clientId/other-assets/new'
    | '/clients/$clientId/accounts/'
    | '/clients/$clientId/other-assets/'
    | '/clients/$clientId/accounts/$accountId/transactions'
    | '/clients/$clientId/accounts/$accountId/'
    | '/clients/$clientId/other-assets/$assetId/'
    | '/clients/$clientId/accounts/$accountId/transactions/$transactionId'
    | '/clients/$clientId/accounts/$accountId/transactions/new'
    | '/clients/$clientId/accounts/$accountId/transactions/'
    | '/clients/$clientId/accounts/$accountId/transactions/$transactionId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ClientsClientIdRouteRoute: typeof ClientsClientIdRouteRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ClientsClientIdRouteRoute: ClientsClientIdRouteRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/login",
        "/profile",
        "/register",
        "/clients/$clientId",
        "/clients/new",
        "/clients/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/clients/$clientId": {
      "filePath": "clients/$clientId/route.tsx",
      "children": [
        "/clients/$clientId/accounts",
        "/clients/$clientId/other-assets",
        "/clients/$clientId/"
      ]
    },
    "/clients/new": {
      "filePath": "clients/new.tsx"
    },
    "/clients/": {
      "filePath": "clients/index.tsx"
    },
    "/clients/$clientId/accounts": {
      "filePath": "clients/$clientId/accounts/route.tsx",
      "parent": "/clients/$clientId",
      "children": [
        "/clients/$clientId/accounts/$accountId",
        "/clients/$clientId/accounts/new",
        "/clients/$clientId/accounts/"
      ]
    },
    "/clients/$clientId/other-assets": {
      "filePath": "clients/$clientId/other-assets/route.tsx",
      "parent": "/clients/$clientId",
      "children": [
        "/clients/$clientId/other-assets/$assetId",
        "/clients/$clientId/other-assets/new",
        "/clients/$clientId/other-assets/"
      ]
    },
    "/clients/$clientId/": {
      "filePath": "clients/$clientId/index.tsx",
      "parent": "/clients/$clientId"
    },
    "/clients/$clientId/accounts/$accountId": {
      "filePath": "clients/$clientId/accounts/$accountId/route.tsx",
      "parent": "/clients/$clientId/accounts",
      "children": [
        "/clients/$clientId/accounts/$accountId/transactions",
        "/clients/$clientId/accounts/$accountId/"
      ]
    },
    "/clients/$clientId/other-assets/$assetId": {
      "filePath": "clients/$clientId/other-assets/$assetId/route.tsx",
      "parent": "/clients/$clientId/other-assets",
      "children": [
        "/clients/$clientId/other-assets/$assetId/"
      ]
    },
    "/clients/$clientId/accounts/new": {
      "filePath": "clients/$clientId/accounts/new.tsx",
      "parent": "/clients/$clientId/accounts"
    },
    "/clients/$clientId/other-assets/new": {
      "filePath": "clients/$clientId/other-assets/new.tsx",
      "parent": "/clients/$clientId/other-assets"
    },
    "/clients/$clientId/accounts/": {
      "filePath": "clients/$clientId/accounts/index.tsx",
      "parent": "/clients/$clientId/accounts"
    },
    "/clients/$clientId/other-assets/": {
      "filePath": "clients/$clientId/other-assets/index.tsx",
      "parent": "/clients/$clientId/other-assets"
    },
    "/clients/$clientId/accounts/$accountId/transactions": {
      "filePath": "clients/$clientId/accounts/$accountId/transactions/route.tsx",
      "parent": "/clients/$clientId/accounts/$accountId",
      "children": [
        "/clients/$clientId/accounts/$accountId/transactions/$transactionId",
        "/clients/$clientId/accounts/$accountId/transactions/new",
        "/clients/$clientId/accounts/$accountId/transactions/"
      ]
    },
    "/clients/$clientId/accounts/$accountId/": {
      "filePath": "clients/$clientId/accounts/$accountId/index.tsx",
      "parent": "/clients/$clientId/accounts/$accountId"
    },
    "/clients/$clientId/other-assets/$assetId/": {
      "filePath": "clients/$clientId/other-assets/$assetId/index.tsx",
      "parent": "/clients/$clientId/other-assets/$assetId"
    },
    "/clients/$clientId/accounts/$accountId/transactions/$transactionId": {
      "filePath": "clients/$clientId/accounts/$accountId/transactions/$transactionId/route.tsx",
      "parent": "/clients/$clientId/accounts/$accountId/transactions",
      "children": [
        "/clients/$clientId/accounts/$accountId/transactions/$transactionId/"
      ]
    },
    "/clients/$clientId/accounts/$accountId/transactions/new": {
      "filePath": "clients/$clientId/accounts/$accountId/transactions/new.tsx",
      "parent": "/clients/$clientId/accounts/$accountId/transactions"
    },
    "/clients/$clientId/accounts/$accountId/transactions/": {
      "filePath": "clients/$clientId/accounts/$accountId/transactions/index.tsx",
      "parent": "/clients/$clientId/accounts/$accountId/transactions"
    },
    "/clients/$clientId/accounts/$accountId/transactions/$transactionId/": {
      "filePath": "clients/$clientId/accounts/$accountId/transactions/$transactionId/index.tsx",
      "parent": "/clients/$clientId/accounts/$accountId/transactions/$transactionId"
    }
  }
}
ROUTE_MANIFEST_END */
